import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
import { extractText, getDocumentProxy } from 'npm:unpdf';

// parseFormI — extract the counterparty agency's details from a Form I
// (Agent-to-Agent Agreement – Sales) PDF generated by the Form I Generator.
//
// The Form I has two columns: AGENT A (Seller's Agent) and AGENT B (Buyer's Agent).
// This function identifies which column belongs to Erudite and returns the OTHER
// column's data for auto-fill. It never writes to any entity.
//
// Input (POST JSON): { file_url | text, debug? }
//
// Output shape:
// {
//   ok: boolean,
//   erudite_side: "seller" | "buyer" | null,   // which column Erudite occupies
//   their_side:   "seller" | "buyer" | null,   // counterparty's column
//   counterparty: {
//     their_side, establishment, address, phone, mobile, email,
//     orn, ded, poBox, agentName, brn, dateIssued, agentMobile, agentEmail
//   } | null,
//   erudite: { erudite_side, establishment, orn, agentName, brn } | null,
//   warnings: string[],
//   note: string
// }

// ─── Erudite identifiers ──────────────────────────────────────────────────────
const ERUDITE_ORN          = '29322';
const ERUDITE_BRN          = '34625';
const ERUDITE_NAME_RE      = /erudite/i;
const ERUDITE_EMAIL_DOMAIN = '@erudite-estate.com';

// ─── Helpers ──────────────────────────────────────────────────────────────────
function normSpaces(s: string): string {
  return s.replace(/ /g, ' ').replace(/­/g, '-');
}

function clean(v: string | null | undefined): string | null {
  if (!v) return null;
  const t = v.trim();
  if (!t || t === '-' || t === 'N/A' || t === 'n/a' || t === '_') return null;
  return t;
}

// Extract a two-column row value for AGENT A and AGENT B.
// Form I rows look like: "LABEL: VALUE_A LABEL: VALUE_B" (x-sorted by unpdf)
// We find the second occurrence of the label and use it as the split point.
function twoCol(text: string, label: string): [string | null, string | null] {
  const esc = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // Match: label: VALUE_A label: VALUE_B  (single-line, non-greedy)
  const re = new RegExp(esc + ':?\\s*([^\\n]*?)\\s+' + esc + ':?\\s*([^\\n]*)', 'i');
  const m = text.match(re);
  if (m) return [clean(m[1]), clean(m[2])];

  // Fallback: label appears on separate lines (one per column, e.g. stream-order extraction)
  // In this case text might be "label: VALUE_A\nlabel: VALUE_B" OR
  // "label: label:\nVALUE_A VALUE_B" — try both
  const fallbackRe = new RegExp(esc + ':?\\s*([^\\n]+)', 'gi');
  const all: string[] = [];
  let fm;
  while ((fm = fallbackRe.exec(text)) !== null) {
    const v = clean(fm[1]);
    if (v) all.push(v);
    if (all.length === 2) break;
  }
  if (all.length === 2) return [all[0], all[1]];
  if (all.length === 1) return [all[0], null];
  return [null, null];
}

// For fields that are short and non-overlapping, extract from a scoped block.
// Used as a stronger fallback when the two-column split is ambiguous.
function singleField(block: string, label: string): string | null {
  const esc = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const m = block.match(new RegExp(esc + ':?\\s*([^\\n:]{1,100})', 'i'));
  return clean(m?.[1] ?? null);
}

// Determine if a parsed party object matches Erudite's known identifiers.
function isErudite(p: Record<string, string | null>): boolean {
  if (p.orn && p.orn.replace(/\s/g, '') === ERUDITE_ORN) return true;
  if (p.brn && p.brn.replace(/\s/g, '') === ERUDITE_BRN) return true;
  if (p.establishment && ERUDITE_NAME_RE.test(p.establishment)) return true;
  if (p.email && p.email.toLowerCase().includes(ERUDITE_EMAIL_DOMAIN)) return true;
  if (p.agentEmail && p.agentEmail.toLowerCase().includes(ERUDITE_EMAIL_DOMAIN)) return true;
  return false;
}

// ─── Main parser ──────────────────────────────────────────────────────────────
function parseFormI(rawText: string): {
  ok: boolean;
  erudite_side: 'seller' | 'buyer' | null;
  their_side: 'seller' | 'buyer' | null;
  counterparty: Record<string, string | null> | null;
  eruditeParty: Record<string, string | null> | null;
  warnings: string[];
  isFormI: boolean;
} {
  const text = normSpaces(rawText);
  const warnings: string[] = [];

  // ── Verify document type ───────────────────────────────────────────────────
  const isFormI =
    /AGENT TO AGENT AGREEMENT/i.test(text) ||
    /FORM\s*I\s*[–-]\s*SALES/i.test(text) ||
    /FORM\s*I\s*[\(\–]/i.test(text);

  if (!isFormI) {
    warnings.push(
      'Document does not appear to be a Form I (Agent-to-Agent Agreement – Sales). ' +
      'Expected header "AGENT TO AGENT AGREEMENT" or "FORM I – SALES" not found.'
    );
  }

  // ── Detect erudite_side from the "— ERUDITE" annotation in column headers ─
  // The Form I Generator stamps "AGENT A (Seller's Agent) — ERUDITE" on Erudite's column.
  let headerSide: 'seller' | 'buyer' | null = null;
  if (/AGENT A[^\n]*—\s*ERUDITE/i.test(text)) headerSide = 'seller';
  else if (/AGENT B[^\n]*—\s*ERUDITE/i.test(text)) headerSide = 'buyer';

  // ── Extract all two-column field pairs ─────────────────────────────────────
  // Each pair gives [agentA_value, agentB_value].
  const [estA, estB]         = twoCol(text, 'Establishment');
  const [addrA, addrB]       = twoCol(text, 'Address');
  const [phoneA, phoneB]     = twoCol(text, 'Phone');
  const [mobileA, mobileB]   = twoCol(text, 'Mobile');
  const [emailA, emailB]     = twoCol(text, 'Email');
  const [ornA, ornB]         = twoCol(text, 'ORN');
  const [dedA, dedB]         = twoCol(text, 'DED Lisc');
  const [poBoxA, poBoxB]     = twoCol(text, 'P\\.O\\. Box');
  const [nameA, nameB]       = twoCol(text, 'Agent Name');
  const [brnA, brnB]         = twoCol(text, 'BRN');
  const [dateA, dateB]       = twoCol(text, 'Date Issued');
  const [agMobA, agMobB]     = twoCol(text, 'Agent Mobile');
  const [agEmailA, agEmailB] = twoCol(text, 'Agent Email');

  const partyA: Record<string, string | null> = {
    establishment: estA, address: addrA, phone: phoneA, mobile: mobileA,
    email: emailA, orn: ornA, ded: dedA, poBox: poBoxA,
    agentName: nameA, brn: brnA, dateIssued: dateA,
    agentMobile: agMobA, agentEmail: agEmailA,
  };
  const partyB: Record<string, string | null> = {
    establishment: estB, address: addrB, phone: phoneB, mobile: mobileB,
    email: emailB, orn: ornB, ded: dedB, poBox: poBoxB,
    agentName: nameB, brn: brnB, dateIssued: dateB,
    agentMobile: agMobB, agentEmail: agEmailB,
  };

  // ── Identify Erudite side ──────────────────────────────────────────────────
  const aIsErudite = isErudite(partyA);
  const bIsErudite = isErudite(partyB);

  // Header annotation is the strongest signal; field matching is the fallback.
  let erudite_side: 'seller' | 'buyer' | null = null;
  let their_side:   'seller' | 'buyer' | null = null;
  let eruditeParty: Record<string, string | null> | null = null;
  let counterparty: Record<string, string | null> | null = null;

  if (headerSide) {
    // Trust the "— ERUDITE" stamp first
    erudite_side = headerSide;
    their_side   = headerSide === 'seller' ? 'buyer' : 'seller';
    eruditeParty = headerSide === 'seller' ? partyA : partyB;
    counterparty = headerSide === 'seller' ? partyB : partyA;

    // Sanity-check against field matching; warn if they disagree
    if ((headerSide === 'seller' && bIsErudite && !aIsErudite) ||
        (headerSide === 'buyer'  && aIsErudite && !bIsErudite)) {
      warnings.push(
        'Column header says Erudite is the ' + headerSide + "'s agent, but field-level " +
        'identifiers (ORN/BRN/email) match the opposite column. ' +
        'The header annotation is being trusted — verify the PDF manually.'
      );
    }
  } else if (aIsErudite && !bIsErudite) {
    erudite_side = 'seller'; their_side = 'buyer';
    eruditeParty = partyA; counterparty = partyB;
  } else if (bIsErudite && !aIsErudite) {
    erudite_side = 'buyer'; their_side = 'seller';
    eruditeParty = partyB; counterparty = partyA;
  } else if (aIsErudite && bIsErudite) {
    warnings.push(
      'Both columns matched Erudite identifiers — possible extraction error or internal form. ' +
      'Cannot determine counterparty. Use debug:true to inspect raw extracted text.'
    );
    return { ok: false, erudite_side: null, their_side: null, counterparty: null, eruditeParty: null, warnings, isFormI };
  } else {
    warnings.push(
      'Neither column matched Erudite identifiers ' +
      '(ORN ' + ERUDITE_ORN + ', BRN ' + ERUDITE_BRN + ', "erudite" name, ' + ERUDITE_EMAIL_DOMAIN + ' email). ' +
      'This may be a Form I between two other agencies, or the PDF layout differs from the expected template. ' +
      'Use debug:true to inspect the raw extracted text and verify field extraction.'
    );
    return { ok: false, erudite_side: null, their_side: null, counterparty: null, eruditeParty: null, warnings, isFormI };
  }

  // ── Minimal-data guard ────────────────────────────────────────────────────
  const hasMinimal = counterparty.establishment || counterparty.orn || counterparty.agentName;
  if (!hasMinimal) {
    warnings.push(
      'Counterparty column was identified but no establishment name, ORN, or agent name ' +
      'could be extracted. The PDF layout may differ from the expected Form I template. ' +
      'Use debug:true to inspect the raw extracted text.'
    );
  }

  return {
    ok: true,
    erudite_side,
    their_side,
    counterparty,
    eruditeParty,
    warnings,
    isFormI,
  };
}

// ─── HTTP handler ─────────────────────────────────────────────────────────────
Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  let user = null;
  try { user = await base44.auth.me(); } catch (_) { /* gate */ }
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  let body: Record<string, unknown> = {};
  try { body = await req.json(); } catch (_) { /* query-only call */ }

  const url    = new URL(req.url);
  const fileUrl = (body.file_url as string | undefined) || url.searchParams.get('file_url') || null;
  let rawText   = (body.text as string | undefined) || null;

  if (!rawText) {
    if (!fileUrl) {
      return Response.json({ error: 'Provide file_url (Base44 storage URL of the Form I PDF) or a text body.' }, { status: 400 });
    }
    try {
      const buf = new Uint8Array(await (await fetch(fileUrl)).arrayBuffer());
      const pdf = await getDocumentProxy(buf);
      const r   = await extractText(pdf, { mergePages: true });
      rawText   = Array.isArray(r.text) ? r.text.join('\n') : (r.text as string);
    } catch (e) {
      return Response.json({
        error: 'PDF extraction failed',
        detail: String(e),
        hint: 'Retry with a { text: "<extracted text>" } body, or check the file_url is accessible.',
      }, { status: 422 });
    }
  }

  // Debug mode — returns raw extracted text so field positions can be inspected.
  if (body.debug === true) {
    return Response.json({
      parser_version: 'v1-form-i',
      raw_text_length: rawText.length,
      raw_text_first_4000: rawText.slice(0, 4000),
      raw_text_full: rawText.length <= 8000 ? rawText : undefined,
    });
  }

  const result = parseFormI(rawText);

  return Response.json({
    parser_version: 'v1-form-i',
    ok:            result.ok,
    is_form_i:     result.isFormI,
    erudite_side:  result.erudite_side,   // "seller" | "buyer" | null
    their_side:    result.their_side,     // "seller" | "buyer" | null
    counterparty: result.ok && result.counterparty ? {
      their_side:       result.their_side,
      establishment:    result.counterparty.establishment,
      address:          result.counterparty.address,
      phone:            result.counterparty.phone,
      mobile:           result.counterparty.mobile,
      email:            result.counterparty.email,
      orn:              result.counterparty.orn,
      ded:              result.counterparty.ded,
      poBox:            result.counterparty.poBox,
      agentName:        result.counterparty.agentName,
      brn:              result.counterparty.brn,
      dateIssued:       result.counterparty.dateIssued,
      agentMobile:      result.counterparty.agentMobile,
      agentEmail:       result.counterparty.agentEmail,
    } : null,
    erudite: result.ok && result.eruditeParty ? {
      erudite_side:  result.erudite_side,
      establishment: result.eruditeParty.establishment,
      orn:           result.eruditeParty.orn,
      agentName:     result.eruditeParty.agentName,
      brn:           result.eruditeParty.brn,
    } : null,
    warnings: result.warnings,
    note: result.ok
      ? `Erudite is the ${result.erudite_side}'s agent. Counterparty (${result.their_side}'s agent) details extracted — review before use.`
      : 'Could not identify the Erudite party — see warnings.',
  });
});
