import {
  Target, Clock, Wallet, FileSignature, Users, KeyRound, Landmark, UserCheck,
} from 'lucide-react';

// Unified question bank — combines the coaching questions from CallBrainPanel
// with the option lists from CallQualificationTab. Each item maps directly to
// a CallQualification form field, so ticking a chip fills the field instantly.

export const QUESTION_BANK = [
  {
    field_key: 'motivation',
    area: 'Motivation',
    Icon: Target,
    question: "What's prompting you to think about selling right now?",
    why: 'Motivation drives everything. A relocating or distressed owner is far more negotiable than someone just testing the market.',
    input_type: 'choice',
    options: [
      { label: 'Relocating', value: 'relocating' },
      { label: 'Cashing Out', value: 'cashing_out' },
      { label: 'Upgrading / Downsizing', value: 'upgrading_downsizing' },
      { label: 'Distressed / Needs Funds', value: 'distressed_need_funds' },
      { label: 'Inherited', value: 'inherited' },
      { label: 'Poor Returns', value: 'poor_returns' },
      { label: 'Just Testing Market', value: 'just_testing_market' },
      { label: 'Other', value: 'other' },
    ],
    notes_field: 'motivation_notes',
    notes_label: "In the owner's own words…",
  },
  {
    field_key: 'timeline_urgency',
    area: 'Timeline / Urgency',
    Icon: Clock,
    question: 'If we brought you the right buyer this month, how quickly would you want to close?',
    why: 'Anchor urgency to a real deadline. "ASAP" with no date usually means no rush. A resale transfer takes 4–6 weeks once under Form F.',
    input_type: 'choice',
    options: [
      { label: 'ASAP / Urgent', value: 'asap_urgent' },
      { label: '1–3 Months', value: '1_3_months' },
      { label: '3–6 Months', value: '3_6_months' },
      { label: '6–12 Months', value: '6_12_months' },
      { label: 'No Rush / Testing', value: 'no_rush_testing' },
      { label: 'Unknown', value: 'unknown' },
    ],
  },
  {
    field_key: 'price_expectation_aed',
    area: 'Price Expectation',
    Icon: Wallet,
    question: 'What figure did you have in mind for the unit?',
    why: 'Ground price against actual DLD closes, not portal asking prices. Portals are aspirational; DLD is truth.',
    input_type: 'number',
    placeholder: 'e.g. 1400000',
    prefix: 'AED',
  },
  {
    field_key: 'price_vs_valuation',
    area: 'Price vs Valuation',
    Icon: Wallet,
    question: 'How does the asking price compare to recent DLD transaction prices for your building?',
    why: 'Tells you if the owner is realistic, aspirational, or motivated enough to accept below market.',
    input_type: 'choice',
    options: [
      { label: 'Realistic', value: 'realistic' },
      { label: 'Slightly High', value: 'slightly_high' },
      { label: 'Significantly Overpriced', value: 'significantly_overpriced' },
      { label: 'Below Market', value: 'below_market' },
      { label: 'Not Discussed', value: 'not_discussed' },
    ],
  },
  {
    field_key: 'mandate_openness',
    area: 'Mandate / Exclusivity',
    Icon: FileSignature,
    question: 'Would you consider giving one agent exclusivity for a short window, so we can invest in photography, portal boosts and a proper launch?',
    why: 'Form A is the RERA listing agreement. Exclusive mandates let you invest in marketing; open listings become a price race to the bottom.',
    input_type: 'choice',
    options: [
      { label: 'Open to Exclusive', value: 'open_to_exclusive' },
      { label: 'Non-Exclusive Only', value: 'non_exclusive_only' },
      { label: 'Already With Other Brokers', value: 'already_with_other_brokers' },
      { label: 'Wants to Self-Sell', value: 'wants_to_self_sell' },
      { label: 'Undecided', value: 'undecided' },
      { label: 'Not Discussed', value: 'not_discussed' },
    ],
  },
  {
    field_key: 'competing_brokers',
    area: 'Competing Brokers',
    Icon: Users,
    question: 'Are other agents already marketing the unit — and roughly how many?',
    why: 'Knowing the competition tells you how to differentiate — and whether the owner is realistic about pricing.',
    input_type: 'text',
    placeholder: 'Which / how many?',
  },
  {
    field_key: 'tenancy_status',
    area: 'Tenancy Status',
    Icon: KeyRound,
    question: 'Is the unit vacant, owner-occupied, or tenanted right now?',
    why: 'A tenanted unit sells to investors; vacant sells to end-users at a premium. Eviction needs 12 months\' notarised notice — flag it early.',
    input_type: 'choice',
    options: [
      { label: 'Vacant', value: 'vacant' },
      { label: 'Tenanted — Lease Active', value: 'tenanted_lease_active' },
      { label: 'Tenanted — Lease Expiring', value: 'tenanted_lease_expiring' },
      { label: 'Owner-Occupied', value: 'owner_occupied' },
      { label: 'Unknown', value: 'unknown' },
    ],
  },
  {
    field_key: 'available_from',
    area: 'Available From',
    Icon: KeyRound,
    question: 'When would the unit be available for handover to a new buyer?',
    why: 'Vacant possession dates affect the buyer pool and the transfer timeline.',
    input_type: 'date',
  },
  {
    field_key: 'mortgage_status',
    area: 'Mortgage Status',
    Icon: Landmark,
    question: 'Is there a mortgage on the property — with a local bank or an overseas one?',
    why: 'A mortgaged sale adds ~2–3 weeks (bank liability letter, blocking, release). Early settlement is capped at 1% or AED 10,000.',
    input_type: 'choice',
    options: [
      { label: 'Free & Clear', value: 'free_and_clear' },
      { label: 'Mortgaged (Local Bank)', value: 'mortgaged_local' },
      { label: 'Mortgaged (Overseas)', value: 'mortgaged_overseas' },
      { label: 'Payment Plan', value: 'payment_plan' },
      { label: 'Unknown', value: 'unknown' },
    ],
  },
  {
    field_key: 'is_decision_maker',
    area: 'Decision Maker',
    Icon: UserCheck,
    question: 'Are you the sole owner on the title deed, or is it jointly held / under a company?',
    why: 'Every owner on the title must sign at transfer. Overseas owners need a UAE-attested POA — line it up before you get an offer.',
    input_type: 'choice',
    options: [
      { label: 'Sole Decision Maker', value: 'sole_decision_maker' },
      { label: 'Joint / Needs Spouse', value: 'joint_needs_spouse' },
      { label: 'Represents Owner', value: 'represents_owner' },
      { label: 'Unknown', value: 'unknown' },
    ],
  },
  {
    field_key: 'call_outcome',
    area: 'Call Outcome',
    Icon: Target,
    question: 'What was the overall outcome of this call?',
    why: 'Sets the next action in the pipeline and triggers the right follow-up sequence.',
    input_type: 'choice',
    options: [
      { label: 'Interested / Proceeding', value: 'interested_proceeding' },
      { label: 'Needs Follow-Up', value: 'needs_followup' },
      { label: 'Callback Requested', value: 'callback_requested' },
      { label: 'Thinking About It', value: 'thinking_about_it' },
      { label: 'Not Ready', value: 'not_ready' },
      { label: 'Not Interested', value: 'not_interested' },
      { label: 'No Answer', value: 'no_answer' },
      { label: 'Wrong Number', value: 'wrong_number' },
      { label: 'Dead Lead', value: 'dead_lead' },
    ],
  },
  {
    field_key: 'rapport_after_call',
    area: 'Rapport After Call',
    Icon: UserCheck,
    question: 'How would you rate the rapport after this call?',
    why: 'Rapport level drives the urgency and approach for the next touchpoint.',
    input_type: 'choice',
    options: [
      { label: 'Cold', value: 'cold' },
      { label: 'Warming', value: 'warming' },
      { label: 'Rapport Built', value: 'rapport_built' },
      { label: 'Trust Established', value: 'trust_established' },
      { label: 'Champion', value: 'champion' },
    ],
  },
  {
    field_key: 'next_step',
    area: 'Next Step',
    Icon: Target,
    question: 'What was the agreed next step?',
    why: 'A clear next step prevents the lead from going cold.',
    input_type: 'text',
    placeholder: 'Agreed next action…',
  },
  {
    field_key: 'followup_date',
    area: 'Follow-Up Date',
    Icon: Clock,
    question: 'When should we follow up?',
    why: 'Lock in a date while the owner is engaged.',
    input_type: 'date',
  },
];

export const DUBAI_FLAGS = [
  'Are all service charges & developer dues cleared? The developer NOC (5–10 days, AED 500–5,000) depends on it.',
  'Selling above AED 2M can affect a Golden Visa tied to the property — check before advising.',
  'Off-plan / pre-handover? Confirm the developer allows resale and what the transfer fee / % paid threshold is.',
];